Update Dockerfile

diff --git a/frontend/nft-master/Dockerfile b/frontend/nft-master/Dockerfile
--- a/frontend/nft-master/Dockerfile
+++ b/frontend/nft-master/Dockerfile
@@ -23,7 +23,12 @@ ENV REACT_APP_NODE_ADDRESS=${REACT_APP_NODE_ADDRESS} \
     REACT_APP_NFT_EXPLORER_URL=${REACT_APP_NFT_EXPLORER_URL} \
     DISABLE_ESLINT_PLUGIN=true
 
-RUN yarn install
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
 RUN yarn build
 
