revert prev Dockerfile; add install dependencies based on the preferred package manager

diff --git a/frontend/nft-master/Dockerfile b/frontend/nft-master/Dockerfile
--- a/frontend/nft-master/Dockerfile
+++ b/frontend/nft-master/Dockerfile
@@ -1,58 +1,36 @@
-# Build stage
-FROM node:18-alpine AS build
-
-WORKDIR /opt/fe
-
-COPY . /opt/fe
-
-ARG REACT_APP_NODE_ADDRESS \
-    REACT_APP_DEFAULT_NODES_URL \
-    REACT_APP_IPFS_ADDRESS \
-    REACT_APP_IPFS_GATEWAY_ADDRESS \
-    REACT_APP_TESTNET_NFT_CONTRACT_ADDRESS \
-    REACT_APP_DEFAULT_CONTRACT_ADDRESS \
-    REACT_APP_DEFAULT_TESTNET_CONTRACT_ADDRESS
-
-ENV REACT_APP_NODE_ADDRESS=${REACT_APP_NODE_ADDRESS} \
-    REACT_APP_DEFAULT_NODES_URL=${REACT_APP_DEFAULT_NODES_URL} \
-    REACT_APP_IPFS_ADDRESS=${REACT_APP_IPFS_ADDRESS} \
-    REACT_APP_IPFS_GATEWAY_ADDRESS=${REACT_APP_IPFS_GATEWAY_ADDRESS} \
-    REACT_APP_TESTNET_NFT_CONTRACT_ADDRESS=${REACT_APP_TESTNET_NFT_CONTRACT_ADDRESS} \
-    REACT_APP_DEFAULT_CONTRACT_ADDRESS=${REACT_APP_DEFAULT_CONTRACT_ADDRESS} \
-    REACT_APP_DEFAULT_TESTNET_CONTRACT_ADDRESS=${REACT_APP_DEFAULT_TESTNET_CONTRACT_ADDRESS} \
-    DISABLE_ESLINT_PLUGIN=true
-
-RUN apk update --no-cache && \
-    apk add --no-cache xsel && \
-    yarn install && \
-    yarn build && \
-    rm -rf /var/cache/apk/*
-
-# Run stage
 FROM node:18-alpine
 
-WORKDIR /opt/fe
+WORKDIR /usr/src
 
-COPY . /opt/fe
-COPY --from=build /opt/fe/dist /opt/fe/dist
-COPY --from=build /opt/fe/node_modules /opt/fe/node_modules
+COPY . /usr/src
+
+RUN apk update
+
+RUN apk add xsel
 
 ARG REACT_APP_NODE_ADDRESS \
     REACT_APP_DEFAULT_NODES_URL \
     REACT_APP_IPFS_ADDRESS \
     REACT_APP_IPFS_GATEWAY_ADDRESS \
     REACT_APP_TESTNET_NFT_CONTRACT_ADDRESS \
-    REACT_APP_DEFAULT_CONTRACT_ADDRESS \
-    REACT_APP_DEFAULT_TESTNET_CONTRACT_ADDRESS
-
+    REACT_APP_DEFAULT_CONTRACT_ADDRESS
 ENV REACT_APP_NODE_ADDRESS=${REACT_APP_NODE_ADDRESS} \
     REACT_APP_DEFAULT_NODES_URL=${REACT_APP_DEFAULT_NODES_URL} \
     REACT_APP_IPFS_ADDRESS=${REACT_APP_IPFS_ADDRESS} \
     REACT_APP_IPFS_GATEWAY_ADDRESS=${REACT_APP_IPFS_GATEWAY_ADDRESS} \
     REACT_APP_TESTNET_NFT_CONTRACT_ADDRESS=${REACT_APP_TESTNET_NFT_CONTRACT_ADDRESS} \
     REACT_APP_DEFAULT_CONTRACT_ADDRESS=${REACT_APP_DEFAULT_CONTRACT_ADDRESS} \
-    REACT_APP_DEFAULT_TESTNET_CONTRACT_ADDRESS=${REACT_APP_DEFAULT_TESTNET_CONTRACT_ADDRESS} \
     DISABLE_ESLINT_PLUGIN=true
+
+# Install dependencies based on the preferred package manager
+RUN \
+if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+elif [ -f package-lock.json ]; then npm ci; \
+elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+else echo "Lockfile not found." && exit 1; \
+fi
+
+RUN yarn build
 
 RUN npm install --global serve
 
